### ISSUE TITLE
Upgrade to Reactive Streams 1.0.0-RC4

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJavaReactiveStreams#142]
We need to upgrade to RC4 and make sure everything is good before Reactive Streams goes to 1.0.0.Final.

**Comment by benjchristensen** [comment]
@alkemist do you have time to play with this in the next 24-48 hours? 

I bumped the version locally and can see the few failing unit tests (after getting it compiling). I have not yet spent the time to grok what I need to change and won't have time today (and likely not tomorrow).

**Comment by ldaley** [comment]
I’ll take a look today.

**Comment by benjchristensen** [comment]
Thanks

**Comment by ldaley** [comment]
I just made it pass… I didn't go through the changes since rc1.

**Comment by benjchristensen** [comment]
Awesome, thank you Luke
