### ISSUE TITLE
Questions/issues about the wrappers

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJavaReactiveStreams#144]
1. Why [synchronize](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/0.x/rxjava-reactive-streams/src/main/java/rx/internal/reactivestreams/PublisherAdapter.java#L34) the source `Observable` all the time?
2. Tracking subscribers is [not thread safe](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/0.x/rxjava-reactive-streams/src/main/java/rx/internal/reactivestreams/PublisherAdapter.java#L39): concurrent subscriptions may step on each other's updates. `Subscriber`s may be in better option to detect multiple subscriptions by the fact they receive multiple `Subscription`s.
3. If `n < 1` then it should return and not [fall-through](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/0.x/rxjava-reactive-streams/src/main/java/rx/internal/reactivestreams/PublisherAdapter.java#L57).
4. If I understand the reactive-streams spec correctly, the `request` and `cancel` methods on the `Subscription` has to be called sequentially because it doesn't mandate such calls to be threadsafe when implementing a `Subscription`. We may need to defensively serialize these [method calls](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/0.x/rxjava-reactive-streams/src/main/java/rx/internal/reactivestreams/SubscriberAdapter.java#L45).

**Comment by ldaley** [comment]
> Why synchronize the source Observable all the time?

Since observables can emit concurrently, but publishers are not allowed to. Other option is to require the user to serialize as they can probably know whether the observable will do this or not, but that seems flakey.

> Tracking subscribers is not thread safe: concurrent subscriptions may step on each other's updates.

Good call. We should fix this.

> Subscribers may be in better option to detect multiple subscriptions by the fact they receive multiple Subscriptions.

That would violate rule 2.12.

> If n < 1 then it should return and not fall-through.

Good catch.

> If I understand the reactive-streams spec correctly, the request and cancel methods on the Subscription has to be called sequentially because it doesn't mandate such calls to be threadsafe when implementing a Subscription. We may need to defensively serialize these method calls.

It would be a shame to block here, but given the low likelihood/frequency of concurrent cancel/requests maybe it's the best thing to do, as opposed to more queuing.

I think just using a lock here is probably good enough.

**Comment by akarnokd** [comment]
> Since observables can emit concurrently

RxJava's own spec forbids this and we rely on this fact inside RxJava.

> It would be a shame to block here

There are two ways to implement the serialization which have tradeoffs:
- by using synchronized emitter loops which may block but lock elision and biased locking may help in synchronous scenarios and
- by using queue-drain logic with atomic wip counter and mpsc/clq queue which work non-blockingly and very well if the queue endpoints are in different threads, but they have the unavoidable atomic increment (or CAS in a fast-path) which limits trivial sequential throughput.

**Comment by akarnokd** [comment]
All remaining issues should be fixed with #147.
