### ISSUE TITLE
SingleAsPublisher throws NullPointerException with Single<Void>

### ISSUE THREAD

**Issue by smulesoft** [ReactiveX/RxJavaReactiveStreams#162]
I am trying to use `RxReactiveStreams` to convert from `rx.Single` to `org.reactivestreams.Publisher`, but it's always throwing an Exception when type is `Void`.

Basically, there is one interface for operating asynchronously with a method called `doSomethingAsync()`. The return value of this method is converted to a `rx.Single`. The problem comes when one implementator of `doSomethingAsync()` returns type `Void` (because there is nothing to return. )

It looks like the exception is thrown [here](https://github.com/ReactiveX/RxJavaReactiveStreams/blob/1c6a64de2c9f5c8bd6c798bd1f53513d214aea30/rxjava-reactive-streams/src/main/java/rx/internal/reactivestreams/SingleAsPublisher.java#L70-L78) as if it was not allowed to have a `null` value. 

A workaround I'm using now is to convert the `rx.Single` to `rx.Completable` before calling `RxReactiveStreams.toPublisher()`.

Here is a test case reproducing the issue:

```java
public Void doSomethingAsync() {
    // Processing...
    return null;
}

@Test
public void emptySingleErrorExit() {
    Observable<Void> empty = Observable.fromCallable(this::doSomethingAsync);
    Single<Void> single = empty.toSingle();
    Publisher<Void> publisher = RxReactiveStreams.toPublisher(single);
    Subscriber<? super Void> subscriber = new Subscriber<Void>() {
        @Override
        public void onSubscribe(Subscription subscription) {
            System.out.println("Unexpected subscription");
        }

        @Override
        public void onNext(Void aVoid) {
            System.out.println(String.format("Unexpected value %s", aVoid));
        }

        @Override
        public void onError(Throwable throwable) {
            System.out.println("Exit with error");
        }

        @Override
        public void onComplete() {
            System.out.println("Exit success");
        }
    };
    publisher.subscribe(subscriber);
    StepVerifier.create(publisher).verifyError(NullPointerException.class);
    StepVerifier.create(publisher).verifyErrorMessage("value");
}
```

**Comment by akarnokd** [comment]
`null`s are not allowed in Reactive Streams hence the exception. You have to turn that `Void` Single into an intermediate form that drops the `null`, such as `toObservable().ignoreElements()`.

**Comment by smulesoft** [comment]
Thanks @akarnokd for your answer. Which one is better in this case?
- `Observable<Void> observable = single.toObservable().ignoreElements();`
- `Completable completable = single.toCompletable();`

**Comment by akarnokd** [comment]
The `Completable` has less overhead.

**Comment by smulesoft** [comment]
Awesome! I'll close the issue because it's working as designed, then. Thanks!
