### ISSUE TITLE
Add toSubscriber conversion

### ISSUE THREAD

**Issue by searler** [ReactiveX/RxJavaReactiveStreams#24]
The [article](http://www.smartjava.org/content/use-reactive-streams-api-combine-akka-streams-rxjava) uses internal implementation code from the 0.3 version, as follows:

```
 val sub = new Subscriber[String]() {
      ...
}
    val subSink = SubscriberSink(new RxSubscriberToRsSubscriberAdapter(sub));
```

This use case seems reasonable, at least in the context of integration with [Akka Streams](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala.html)

That would require that `toSubscriber` methods be added to `RxReactiveStreams`

**Comment by ldaley** [comment]
We would add this as `RxReactiveStreams.toSubscriber()`.
